### ISSUE TITLE
Adding Your Projects

### ISSUE THREAD

**Issue by BloxyGithub** [locness3/locness3.github.io#1]
Could you add all your projects on the website?
btw do you want a domain?

**Comment by locness3** [comment]
@BloxyGithub I will see what other projects I can add.

BTW, why are you asking if I want a domain ?

**Comment by locness3** [comment]
@BloxyGithub I've added LennyHome

**Comment by locness3** [comment]
@BloxyGithub I've added my userstyles

**Comment by locness3** [comment]
Actually, what other projects do you except @BloxyGithub ?

**Comment by BloxyGithub** [comment]
any :P

**Comment by locness3** [comment]
> any :P

:thinking:

**Comment by BloxyGithub** [comment]
?

**Comment by locness3** [comment]
thinking emoji

**Comment by BloxyGithub** [comment]
Oh, im dumb
